[project]
name = "iaLib"
version = "0.2.0"
description = "Entorn per realitzar jocs. Forma part de l'assignatura de Intel·ligència Artificial (21722) de la UIB."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
]
